import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.model;  // Mengimpor class Model dari package model


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author azmik
 */
public class ResepForm extends javax.swing.JFrame {
    private model model;
    
    /**
     * Creates new form ResepForm
     */
    public ResepForm() {
        model = new model(); // Inisialisasi Model
        initComponents();
        
        // Menghubungkan JList dengan Model
        listResep.setModel(model.getListModel());
        DefaultTableModel tableModel = new DefaultTableModel(new String[]{"Nama Resep", "Detail Resep", "Jenis Resep"}, 0);
    tableResep.setModel(tableModel);  // Menghubungkan JTable dengan DefaultTableModel
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNamaResep = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaResep = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        btnTambahResep = new javax.swing.JButton();
        btnUbahResep = new javax.swing.JButton();
        btnHapusResep = new javax.swing.JButton();
        comboBoxJenisMakanan = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableResep = new javax.swing.JTable();
        btnExportResep = new javax.swing.JButton();
        btnImportResep = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listResep = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("APLIKASI RESEP MAKANAN");

        jLabel2.setText("Nama Resep    :");

        txtAreaResep.setColumns(20);
        txtAreaResep.setRows(5);
        jScrollPane1.setViewportView(txtAreaResep);

        jLabel3.setText("Detail Resep    :  ");

        btnTambahResep.setBackground(new java.awt.Color(102, 204, 255));
        btnTambahResep.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahResep.setText("Tambah");
        btnTambahResep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahResepActionPerformed(evt);
            }
        });

        btnUbahResep.setText("Ubah");
        btnUbahResep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahResepActionPerformed(evt);
            }
        });

        btnHapusResep.setBackground(new java.awt.Color(255, 102, 102));
        btnHapusResep.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusResep.setText("Hapus");
        btnHapusResep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusResepActionPerformed(evt);
            }
        });

        comboBoxJenisMakanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman" }));

        jLabel5.setText("Jenis                 :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTambahResep)
                        .addGap(31, 31, 31)
                        .addComponent(btnUbahResep)
                        .addGap(29, 29, 29)
                        .addComponent(btnHapusResep))
                    .addComponent(txtNamaResep)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                    .addComponent(comboBoxJenisMakanan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNamaResep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboBoxJenisMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahResep)
                    .addComponent(btnUbahResep)
                    .addComponent(btnHapusResep))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        tableResep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Nama Resep", "Detail Resep", "Jenis Resep"
            }
        ));
        jScrollPane3.setViewportView(tableResep);

        btnExportResep.setBackground(new java.awt.Color(102, 204, 255));
        btnExportResep.setForeground(new java.awt.Color(255, 255, 255));
        btnExportResep.setText("Export");
        btnExportResep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportResepActionPerformed(evt);
            }
        });

        btnImportResep.setText("Import");
        btnImportResep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportResepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnImportResep)
                        .addGap(29, 29, 29)
                        .addComponent(btnExportResep)
                        .addGap(10, 10, 10))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExportResep)
                    .addComponent(btnImportResep))
                .addGap(184, 184, 184))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("LIST RESEP");

        jScrollPane2.setViewportView(listResep);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahResepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahResepActionPerformed
String namaResep = txtNamaResep.getText();
    String detailResep = txtAreaResep.getText();
    String jenisResep = (String) comboBoxJenisMakanan.getSelectedItem(); // Mendapatkan jenis resep yang dipilih

    if (!namaResep.isEmpty() && !detailResep.isEmpty()) {
        // Menambahkan ke JList menggunakan Model
        model.addElement(namaResep);  // Menambahkan nama resep ke JList

        // Menambahkan ke JTable
        DefaultTableModel tableModel = (DefaultTableModel) tableResep.getModel();
        tableModel.addRow(new Object[]{namaResep, detailResep, jenisResep}); // Menambahkan data resep ke tabel

        // Mengosongkan TextField dan TextArea setelah data ditambahkan
        txtNamaResep.setText("");
        txtAreaResep.setText("");
        comboBoxJenisMakanan.setSelectedIndex(0); // Reset ComboBox ke item pertama
    } else {
        JOptionPane.showMessageDialog(null, "Nama resep dan detail resep tidak boleh kosong!");
    }
    }//GEN-LAST:event_btnTambahResepActionPerformed

    private void btnImportResepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportResepActionPerformed
        // TODO add your handling code here:
        // Membuka JFileChooser untuk memilih file
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Open Resep File");
    int userSelection = fileChooser.showOpenDialog(null);

    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File fileToOpen = fileChooser.getSelectedFile();
        
        // Membaca isi file dan menambahkan ke JList
        try (BufferedReader reader = new BufferedReader(new FileReader(fileToOpen))) {
            String line;
            while ((line = reader.readLine()) != null) {
                model.addElement(line); // Menambahkan nama resep ke JList
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat membuka file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnImportResepActionPerformed

    private void btnUbahResepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahResepActionPerformed
     // TODO add your handling code here:
     int selectedIndex = tableResep.getSelectedRow();  // Mendapatkan indeks baris yang dipilih dari JTable
    
    if (selectedIndex != -1) {  // Pastikan ada baris yang dipilih
        // Menampilkan dialog untuk memasukkan nama dan detail resep baru
        String newNamaResep = JOptionPane.showInputDialog("Masukkan nama resep baru:");
        String newDetailResep = JOptionPane.showInputDialog("Masukkan detail resep baru:");
        
        // Pastikan input tidak kosong
        if (newNamaResep != null && !newNamaResep.isEmpty() && newDetailResep != null && !newDetailResep.isEmpty()) {
            // Mengubah nilai di JTable
            DefaultTableModel tableModel = (DefaultTableModel) tableResep.getModel();
            tableModel.setValueAt(newNamaResep, selectedIndex, 0); // Mengubah Nama Resep di JTable
            tableModel.setValueAt(newDetailResep, selectedIndex, 1); // Mengubah Detail Resep di JTable
            
            // Mengubah nilai di JList
            DefaultListModel<String> listModel = (DefaultListModel<String>) listResep.getModel();
            listModel.set(selectedIndex, newNamaResep);  // Mengubah nama resep di JList sesuai dengan index yang sama
        }
    } else {
        JOptionPane.showMessageDialog(null, "Pilih resep yang ingin diubah!");
    }
    }//GEN-LAST:event_btnUbahResepActionPerformed

    private void btnHapusResepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusResepActionPerformed
        // TODO add your handling code here:
        // Mendapatkan indeks baris yang dipilih dari JTable
    int selectedIndex = tableResep.getSelectedRow();  
    
    if (selectedIndex != -1) {  // Pastikan ada baris yang dipilih
        // Menghapus baris dari JTable
        DefaultTableModel tableModel = (DefaultTableModel) tableResep.getModel();
        tableModel.removeRow(selectedIndex); // Menghapus baris yang dipilih dari JTable

        // Menghapus nama resep dari JList
        DefaultListModel<String> listModel = (DefaultListModel<String>) listResep.getModel();
        listModel.remove(selectedIndex); // Menghapus nama resep dari JList pada indeks yang sama
    } else {
        JOptionPane.showMessageDialog(null, "Pilih resep yang ingin dihapus!");
    }
    }//GEN-LAST:event_btnHapusResepActionPerformed

    private void btnExportResepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportResepActionPerformed
        // TODO add your handling code here:
        // Membuka JFileChooser untuk memilih lokasi dan nama file
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Save Daftar Resep to File");
    fileChooser.setSelectedFile(new File("daftar_resep.txt"));  // Default file name
    int userSelection = fileChooser.showSaveDialog(null);

    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File fileToSave = fileChooser.getSelectedFile();
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileToSave))) {
            // Menulis nama resep dari JList
            DefaultListModel<String> listModel = (DefaultListModel<String>) listResep.getModel();
            writer.write("Daftar Nama Resep:\n");
            for (int i = 0; i < listModel.getSize(); i++) {
                writer.write(listModel.getElementAt(i) + "\n");  // Menyimpan setiap nama resep ke file
            }

            // Menulis data lengkap (nama resep, detail resep, jenis resep) dari JTable
            DefaultTableModel tableModel = (DefaultTableModel) tableResep.getModel();
            writer.write("\nDaftar Resep Lengkap:\n");
            for (int i = 0; i < tableModel.getRowCount(); i++) {
                String namaResep = (String) tableModel.getValueAt(i, 0);  // Nama Resep
                String detailResep = (String) tableModel.getValueAt(i, 1);  // Detail Resep
                String jenisResep = (String) tableModel.getValueAt(i, 2);  // Jenis Resep (Makanan/Minuman)
                writer.write(namaResep + " | " + detailResep + " | " + jenisResep + "\n");  // Menyimpan data lengkap ke file
            }

            // Menampilkan pesan sukses
            JOptionPane.showMessageDialog(null, "Daftar resep berhasil disimpan!");
        } catch (IOException e) {
            // Menangani kesalahan saat menulis ke file
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menyimpan file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnExportResepActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResepForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResepForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResepForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResepForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResepForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportResep;
    private javax.swing.JButton btnHapusResep;
    private javax.swing.JButton btnImportResep;
    private javax.swing.JButton btnTambahResep;
    private javax.swing.JButton btnUbahResep;
    private javax.swing.JComboBox<String> comboBoxJenisMakanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listResep;
    private javax.swing.JTable tableResep;
    private javax.swing.JTextArea txtAreaResep;
    private javax.swing.JTextField txtNamaResep;
    // End of variables declaration//GEN-END:variables
}
